import { Router } from "express";
import { getPaymentStats } from "../controllers/payment.controller";

/**
 * Router: Payment Routes
 * 
 * Base path: /api/payments
 * 
 * This router manages all payment-related endpoints for the admin dashboard.
 * Documentation is automatically generated by Swagger using the @swagger tags.
 */
const router = Router();

/**
 * @swagger
 * tags:
 *   name: Payments
 *   description: Payment management and statistics for the admin dashboard
 */

/**
 * GET /api/payments/stats
 * Returns the high-level financial summary shown in the "Payments" tab headers.
 */
router.get("/stats", getPaymentStats);

export default router;
